# Subimos el backup a S3
name: 'Upload Backup to S3'
description: 'Upload backup file to Amazon S3 bucket'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  backup-file-name:
    description: 'Name of the backup file in S3'
    required: true
  backup-dir:
    description: 'Directory where the backup file is located'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install awscli

    - name: Setup credentials
      shell: bash
      run: |
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key-id }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-access-key }}" >> ~/.aws/credentials

    - name: Upload backup to S3
      shell: bash
      run: |
        aws s3 cp ${{ github.workspace }}/${{ inputs.backup-dir }}/${{ inputs.backup-file-name }} s3://aws-bucket-portfolio-01/${{ inputs.backup-file-name }}
      env:
        AWS_DEFAULT_REGION: us-east-2 # Cambia esto a la región de tu bucket S3