# Subimos el backup a S3
name: 'Upload Backup to S3'
description: 'Upload backup file to Amazon S3 bucket'
inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  backup-file-name:
    description: 'Name of the backup file in S3'
    required: true
  backup-dir:
    description: 'Directory where the backup file is located'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    - name: Move inside backup directory
      shell: bash
      run: |
        ls
        echo "Moving to backup directory: tmp"
        cd tmp
        ls
        echo "Moving to backup directory: backup-mongo"
        cd backup-mongo
        ls

    - name: Upload backup to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude "*"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: 'us-east-2'
        AWS_S3_BUCKET: 'aws-bucket-portfolio-01'
        SOURCE_DIR: ${{ github.workspace }}/${{ inputs.backup_dir }}/${{ inputs.backup-file-name }}
