name: Deploy MongoDB Atlas Database

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: terraform
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Terraform version
              run: terraform version

            - name: Create terraform.tfvars
              run: |
                cat <<EOF > terraform/terraform.tfvars
                public_key   = "${{ secrets.TF_VAR_PUBLIC_KEY }}"
                private_key  = "${{ secrets.TF_VAR_PRIVATE_KEY }}"
                project_name = "${{ secrets.TF_VAR_PROJECT_NAME }}"
                org_id       = "${{ secrets.TF_VAR_ORG_ID }}"
                cluster_name = "${{ secrets.TF_VAR_CLUSTER_NAME }}"
                public_ip    = "${{ secrets.TF_VAR_PUBLIC_IP }}"
                password     = "${{ secrets.TF_VAR_PASSWORD }}"
                username     = "${{ secrets.TF_VAR_USERNAME }}"
                EOF

            - name: Initialize Terraform
              run: terraform init

            - name: Apply Terraform configuration
              run: terraform apply -auto-approve