name: Deploy MongoDB Atlas Database

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: terraform
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y unzip

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Create terraform.tfvars
              run: |
                cat <<EOF > terraform.tfvars
                public_key   = "${{ secrets.TF_VAR_PUBLIC_KEY }}"
                private_key  = "${{ secrets.TF_VAR_PRIVATE_KEY }}"
                project_name = "${{ secrets.TF_VAR_PROJECT_NAME }}"
                org_id       = "${{ secrets.TF_VAR_ORG_ID }}"
                cluster_name = "${{ secrets.TF_VAR_CLUSTER_NAME }}"
                public_ip    = "${{ secrets.TF_VAR_PUBLIC_IP }}"
                password     = "${{ secrets.TF_VAR_PASSWORD }}"
                username     = "${{ secrets.TF_VAR_USERNAME }}"
                EOF

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2

            - name: Initialize Terraform
              id: init
              run: terraform init

            - name: Apply Terraform configuration
              run: terraform apply -auto-approve